<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Controle de Acesso</title>
</head>
<body>
    <div>
        <ul>
            <li><a href="/webservice/index/inserir-acesso"><strong>Inserir Acesso</strong></a></li>
            <li><a href="/webservice/index/inserir-horario"><strong>Inserir Horario</strong></a></li>
        </ul>
    </div>
</body>
</html>